# Generated by Django 3.2 on 2022-04-12 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.CharField(default='a3:be:cd:3f:94:0c', max_length=200)),
                ('dev_type', models.CharField(choices=[('emeter', 'emeter'), ('zigbee', 'zigbee'), ('lora', 'lora'), ('gsm', 'gsm')], max_length=120)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Endpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api.devices')),
            ],
            options={
                'db_table': 'endpoints',
            },
        ),
    ]
